[context.production.environment]
  HUGO_VERSION = "0.83.1"

[[redirects]]
  from = "/feed"
  to = "/index.xml"
  status = 200
  force = false

[[redirects]]
  from = "/weblog/2014/solving-fizzbuzz-with-hypermedia"
  to = "/posts/2014/04/solving-fizzbuzz-with-hypermedia"
  status = 200
