[book]
authors = ["Stephen Mizell"]
language = "en"
multilingual = false
src = "src"
title = "The Language-Oriented Approach to API Development"
description = "An approach that encourages people to create a their own language for the way they talk about APIs and to capture that language in a DSL."
